version: '3.8'

services:
  app:
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    depends_on:
      - postgres-db
    environment:
      - HOST_URL:http://localhost:8080
      - TEST_MAIL:jira4jr@gmail.com
      - DATASOURCE_URL:jdbc:postgresql://postgres-db:5432/jira
      - DATASOURCE_USERNAME:jira
      - DATASOURCE_PASSWORD:JiraRush
      - GITHUB_CLIENT_ID:3d0d8738e65881fff266
      - GITHUB_CLIENT_SECRET:0f97031ce6178b7dfb67a6af587f37e222a16120
      - GOOGLE_CLIENT_ID:329113642700-f8if6pu68j2repq3ef6umd5jgiliup60.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET: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
      - GITLAB_CLIENT_ID:b8520a3266089063c0d8261cce36971defa513f5ffd9f9b7a3d16728fc83a494
      - GITLAB_CLIENT_SECRET:e72c65320cf9d6495984a37b0f9cc03ec46be0bb6f071feaebbfe75168117004
      - GITLAB_CLIENT_NAME:GitLab
      - GITLAB_REDIRECT_URI:"{baseUrl}/login/oauth2/code/{registrationId}"
      - GITLAB_AUTHORIZATION_URI:https://gitlab.com/oauth/authorize
      - GITLAB_TOKEN_URI:https://gitlab.com/oauth/token
      - GITLAB_USER_INFO_URI:https://gitlab.com/api/v4/user
      - MAIL_HOST:smtp.gmail.com
      - MAIL_USERNAME:jira4jr@gmail.com
      - MAIL_PASSWORD:zdfzsrqvgimldzyj
      - MAIL_PORT:587

  postgres-db:
    image: 'postgres'
    container_name: postgres-db
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=jira
      - POSTGRES_PASSWORD=JiraRush
      - POSTGRES_DB=jira
      - PGDATA=/var/lib/postgresql/data/pgdata
      